import jsPDF from "jspdf";
import type { AnalysisResult, ProfileAnalysisResult } from "@shared/schema";

function addHeader(doc: jsPDF, title: string, subtitle: string) {
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("RepoScan Report", 20, 25);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("GitHub Intelligence for Hiring", 20, 32);
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 36, 190, 36);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, 20, 46);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(subtitle, 20, 52);
  doc.setTextColor(0, 0, 0);
  return 60;
}

function addSection(doc: jsPDF, y: number, title: string): number {
  if (y > 260) {
    doc.addPage();
    y = 20;
  }
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(title, 20, y);
  doc.setDrawColor(220, 220, 220);
  doc.line(20, y + 2, 190, y + 2);
  return y + 8;
}

function addKeyValue(doc: jsPDF, y: number, key: string, value: string): number {
  if (y > 275) {
    doc.addPage();
    y = 20;
  }
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(key + ":", 20, y);
  doc.setFont("helvetica", "normal");
  doc.text(value, 65, y);
  return y + 5;
}

function addBulletList(doc: jsPDF, y: number, items: string[], indent = 24): number {
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  for (const item of items) {
    if (y > 275) {
      doc.addPage();
      y = 20;
    }
    doc.text("•  " + item, indent, y);
    y += 4.5;
  }
  return y;
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by RepoScan — ${new Date().toLocaleDateString()} — Page ${i} of ${pageCount}`,
      105,
      290,
      { align: "center" }
    );
  }
}

export function exportProfilePDF(data: ProfileAnalysisResult) {
  const doc = new jsPDF();
  const name = data.user.name || data.user.login;
  let y = addHeader(doc, `Candidate Report: ${name}`, `@${data.user.login} — ${data.hiringInsights.experienceLevel} Developer`);

  y = addSection(doc, y, "Overview");
  y = addKeyValue(doc, y, "Recommendation", data.hiringInsights.recommendation);
  y = addKeyValue(doc, y, "Experience Level", data.hiringInsights.experienceLevel);
  y = addKeyValue(doc, y, "Profile Score", `${data.profileScore.total}/100 (${data.profileScore.label})`);
  y = addKeyValue(doc, y, "Code Quality", data.hiringInsights.repoQuality);
  y = addKeyValue(doc, y, "Collaboration", data.hiringInsights.collaborationIndicator);
  y = addKeyValue(doc, y, "Project Diversity", data.hiringInsights.projectDiversity);
  y += 2;

  y = addSection(doc, y, "Profile Details");
  y = addKeyValue(doc, y, "Location", data.user.location || "Not specified");
  y = addKeyValue(doc, y, "Company", data.user.company || "Not specified");
  y = addKeyValue(doc, y, "Repositories", String(data.repos.length));
  y = addKeyValue(doc, y, "Total Stars", String(data.totalStars));
  y = addKeyValue(doc, y, "Total Forks", String(data.totalForks));
  y = addKeyValue(doc, y, "Followers", String(data.user.followers));
  y = addKeyValue(doc, y, "Primary Skills", data.hiringInsights.primarySkills.join(", ") || "—");
  y += 2;

  y = addSection(doc, y, "Summary");
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  const summaryLines = doc.splitTextToSize(data.hiringInsights.summary, 165);
  doc.text(summaryLines, 20, y);
  y += summaryLines.length * 4 + 4;

  if (data.hiringInsights.strengths.length > 0) {
    y = addSection(doc, y, "Strengths");
    y = addBulletList(doc, y, data.hiringInsights.strengths);
    y += 2;
  }

  if (data.hiringInsights.concerns.length > 0) {
    y = addSection(doc, y, "Areas of Concern");
    y = addBulletList(doc, y, data.hiringInsights.concerns);
    y += 2;
  }

  if (data.hiringInsights.redFlags && data.hiringInsights.redFlags.length > 0) {
    y = addSection(doc, y, "Red Flags");
    y = addBulletList(doc, y, data.hiringInsights.redFlags);
    y += 2;
  }

  if (data.hiringInsights.topProjects.length > 0) {
    y = addSection(doc, y, "Top Projects");
    for (const proj of data.hiringInsights.topProjects) {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text(`${proj.pinned ? "[Pinned] " : ""}${proj.name}`, 24, y);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      const meta = [proj.language, `Stars: ${proj.stars}`].filter(Boolean).join(" · ");
      doc.text(meta, 24, y + 4);
      if (proj.description) {
        doc.setTextColor(100, 100, 100);
        const descLines = doc.splitTextToSize(proj.description, 155);
        doc.text(descLines[0], 24, y + 8);
        doc.setTextColor(0, 0, 0);
      }
      y += proj.description ? 14 : 10;
    }
  }

  y += 4;
  y = addSection(doc, y, "Score Breakdown");
  const bd = data.profileScore.breakdown;
  y = addKeyValue(doc, y, "Repos", `${bd.repos}/25`);
  y = addKeyValue(doc, y, "Stars", `${bd.stars}/25`);
  y = addKeyValue(doc, y, "Followers", `${bd.followers}/20`);
  y = addKeyValue(doc, y, "Diversity", `${bd.diversity}/15`);
  y = addKeyValue(doc, y, "Consistency", `${bd.consistency}/15`);

  addFooter(doc);
  doc.save(`reposcan-${data.user.login}-report.pdf`);
}

export function exportRepoPDF(data: AnalysisResult) {
  const doc = new jsPDF();
  let y = addHeader(doc, `Repository: ${data.repo.full_name}`, data.repo.description || "No description");

  y = addSection(doc, y, "Overview");
  y = addKeyValue(doc, y, "Quality Score", `${data.score.total}/100 (${data.score.label})`);
  y = addKeyValue(doc, y, "Stars", String(data.repo.stargazers_count));
  y = addKeyValue(doc, y, "Forks", String(data.repo.forks_count));
  y = addKeyValue(doc, y, "Open Issues", String(data.repo.open_issues_count));
  y = addKeyValue(doc, y, "Primary Language", data.repo.language || "—");
  y = addKeyValue(doc, y, "License", data.repo.license?.name || "None");
  y += 2;

  if (data.complexity) {
    y = addSection(doc, y, "Complexity Analysis");
    y = addKeyValue(doc, y, "Level", data.complexity.level);
    y = addKeyValue(doc, y, "Files", String(data.complexity.fileCount));
    y = addKeyValue(doc, y, "Folders", String(data.complexity.folderCount));
    y = addKeyValue(doc, y, "Languages", String(data.complexity.languageCount));
    y = addKeyValue(doc, y, "Contributors", String(data.complexity.contributorCount));
    if (data.complexity.indicators.length > 0) {
      y = addBulletList(doc, y + 2, data.complexity.indicators);
    }
    y += 2;
  }

  if (data.health) {
    y = addSection(doc, y, "Health Monitor");
    y = addKeyValue(doc, y, "Status", data.health.status);
    y = addKeyValue(doc, y, "Activity", data.health.activityLevel);
    y = addKeyValue(doc, y, "Maintenance", data.health.maintenance);
    y = addKeyValue(doc, y, "Issue Resolution", data.health.issueResolution);
    y += 2;
  }

  y = addSection(doc, y, "Score Breakdown");
  const sb = data.score.breakdown;
  y = addKeyValue(doc, y, "Stars", `${sb.stars}/25`);
  y = addKeyValue(doc, y, "Contributors", `${sb.contributors}/20`);
  y = addKeyValue(doc, y, "Commit Frequency", `${sb.commitFrequency}/20`);
  y = addKeyValue(doc, y, "README", `${sb.hasReadme}/15`);
  y = addKeyValue(doc, y, "Issue Ratio", `${sb.issueRatio}/10`);
  y = addKeyValue(doc, y, "Documentation", `${sb.documentation}/10`);
  y += 2;

  if (data.techStack.length > 0) {
    y = addSection(doc, y, "Tech Stack");
    const stackNames = data.techStack.map(t => `${t.name} (${t.category})`);
    y = addBulletList(doc, y, stackNames);
    y += 2;
  }

  const langEntries = Object.entries(data.languages);
  if (langEntries.length > 0) {
    y = addSection(doc, y, "Languages");
    const total = langEntries.reduce((s, [, v]) => s + v, 0);
    const langList = langEntries
      .sort((a, b) => b[1] - a[1])
      .map(([lang, bytes]) => `${lang}: ${((bytes / total) * 100).toFixed(1)}%`);
    y = addBulletList(doc, y, langList);
  }

  addFooter(doc);
  doc.save(`reposcan-${data.repo.full_name.replace("/", "-")}-report.pdf`);
}
